/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 ./public/cube.glb 
*/

import React, { useRef, forwardRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


export default forwardRef(function Cube(props, ref) {
  // const group = useRef()
  const { nodes, materials } = useGLTF('/cube.glb')

  return (
    <group ref={ref} {...props} dispose={null}>
    

        <group name="cube_1" position={[-1.01, -1.01, -1.01]} rotation={[Math.PI, 1.571, 0]}>
          <mesh name="Cube070" geometry={nodes.Cube070.geometry} material={materials['white.015']} />
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials['blue.010']} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials['orange.010']} />
        </group>

        <group name="cube_2" position={[0, -1.01, -1.01]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Cube069" geometry={nodes.Cube069.geometry} material={materials['white.014']} />
          <mesh name="Cube069_1" geometry={nodes.Cube069_1.geometry} material={materials['orange.009']} />
        </group>

        <group name="cube_3" position={[1.01, -1.01, -1.01]} rotation={[0, 0, Math.PI]}>
          <mesh name="Cube071" geometry={nodes.Cube071.geometry} material={materials['white.016']} />
          <mesh name="Cube071_1" geometry={nodes.Cube071_1.geometry} material={materials['orange.011']} />
          <mesh name="Cube071_2" geometry={nodes.Cube071_2.geometry} material={materials['green.008']} />
        </group>

        <group name="cube_4" position={[-1.01, -1.01, 0]} rotation={[Math.PI, Math.PI / 2, 0]}>
          <mesh name="Cube066" geometry={nodes.Cube066.geometry} material={materials['white.011']} />
          <mesh name="Cube066_1" geometry={nodes.Cube066_1.geometry} material={materials['blue.009']} />
        </group>

        <mesh name="cube_5" geometry={nodes.cube_5.geometry} material={materials['white.010']} position={[0, -1.01, 0]} />


        <group name="cube_6" position={[1.01, -1.01, 0]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
          <mesh name="Cube068" geometry={nodes.Cube068.geometry} material={materials['white.013']} />
          <mesh name="Cube068_1" geometry={nodes.Cube068_1.geometry} material={materials['green.007']} />
        </group>

        <group name="cube_7" position={[-1.01, -1.01, 1.01]} rotation={[-Math.PI, 0, 0]}>
          <mesh name="Cube073" geometry={nodes.Cube073.geometry} material={materials['white.018']} />
          <mesh name="Cube073_1" geometry={nodes.Cube073_1.geometry} material={materials['red.009']} />
          <mesh name="Cube073_2" geometry={nodes.Cube073_2.geometry} material={materials['blue.011']} />
        </group>

        <group name="cube_8" position={[0, -1.01, 1.01]} rotation={[Math.PI, 0, 0]}>
          <mesh name="Cube067" geometry={nodes.Cube067.geometry} material={materials['white.012']} />
          <mesh name="Cube067_1" geometry={nodes.Cube067_1.geometry} material={materials['red.008']} />
        </group>

        <group name="cube_9" position={[1.01, -1.01, 1.01]} rotation={[-Math.PI, -Math.PI / 2, 0]}>
          <mesh name="Cube074" geometry={nodes.Cube074.geometry} material={materials['white.019']} />
          <mesh name="Cube074_1" geometry={nodes.Cube074_1.geometry} material={materials['green.010']} />
          <mesh name="Cube074_2" geometry={nodes.Cube074_2.geometry} material={materials['red.010']} />
        </group>


        <group name="cube_10" position={[-1.01, 0, -1.01]} rotation={[0, 0, Math.PI / 2]}>
          <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials['blue.003']} />
          <mesh name="Cube052_1" geometry={nodes.Cube052_1.geometry} material={materials['orange.004']} />
        </group>

        <mesh name="cube_11" geometry={nodes.cube_11.geometry} material={materials['orange.003']} position={[0, 0, -1.01]} />

        <group name="cube_12" position={[1.01, 0, -1.01]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={materials['green.002']} />
          <mesh name="Cube053_1" geometry={nodes.Cube053_1.geometry} material={materials['orange.005']} />
        </group>

        <mesh name="cube_13" geometry={nodes.cube_13.geometry} material={materials['blue.002']} position={[-1.01, 0, 0]} />

        <mesh name="cube_14" geometry={nodes.cube_14.geometry} material={materials['white.009']} />
        <mesh name="cube_15" geometry={nodes.cube_15.geometry} material={materials['green.001']} position={[1.01, 0, 0]} />

        <group name="cube_16" position={[-1.01, 0, 1.01]} rotation={[Math.PI, 0, Math.PI / 2]}>
          <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={materials['blue.004']} />
          <mesh name="Cube054_1" geometry={nodes.Cube054_1.geometry} material={materials['red.003']} />
        </group>


        <mesh name="cube_17" geometry={nodes.cube_17.geometry} material={materials['red.002']} position={[0, 0, 1.01]} />


        <group name="cube_18" position={[1.01, 0, 1.01]} rotation={[Math.PI, 0, -Math.PI / 2]}>
          <mesh name="Cube055" geometry={nodes.Cube055.geometry} material={materials['green.003']} />
          <mesh name="Cube055_1" geometry={nodes.Cube055_1.geometry} material={materials['red.004']} />
        </group>


        <group name="cube_19" position={[-1.01, 1.01, -1.01]}>
          <mesh name="Cube061" geometry={nodes.Cube061.geometry} material={materials['Yellow.007']} />
          <mesh name="Cube061_1" geometry={nodes.Cube061_1.geometry} material={materials['orange.007']} />
          <mesh name="Cube061_2" geometry={nodes.Cube061_2.geometry} material={materials['blue.007']} />
        </group>



        <group name="cube_20" position={[0, 1.01, -1.01]}>
          <mesh name="Cube060" geometry={nodes.Cube060.geometry} material={materials['Yellow.006']} />
          <mesh name="Cube060_1" geometry={nodes.Cube060_1.geometry} material={materials['orange.006']} />
        </group>

        <group name="cube_21" position={[1.01, 1.01, -1.01]} rotation={[0, -1.571, 0]}>
          <mesh name="Cube062" geometry={nodes.Cube062.geometry} material={materials['Yellow.008']} />
          <mesh name="Cube062_1" geometry={nodes.Cube062_1.geometry} material={materials['green.005']} />
          <mesh name="Cube062_2" geometry={nodes.Cube062_2.geometry} material={materials['orange.008']} />
        </group>


        <group name="cube_22" position={[-1.01, 1.01, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh name="Cube058" geometry={nodes.Cube058.geometry} material={materials['Yellow.004']} />
          <mesh name="Cube058_1" geometry={nodes.Cube058_1.geometry} material={materials['blue.005']} />
        </group>

        <mesh name="cube_23" geometry={nodes.cube_23.geometry} material={materials['Yellow.002']} position={[0, 1.01, 0]} />


        <group name="cube_24" position={[1.01, 1.01, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={materials['Yellow.005']} />
          <mesh name="Cube059_1" geometry={nodes.Cube059_1.geometry} material={materials['green.004']} />
        </group>

        <group name="cube_25" position={[-1.01, 1.01, 1.01]} rotation={[0, 1.571, 0]}>
          <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={materials['Yellow.010']} />
          <mesh name="Cube064_1" geometry={nodes.Cube064_1.geometry} material={materials['blue.008']} />
          <mesh name="Cube064_2" geometry={nodes.Cube064_2.geometry} material={materials['red.007']} />
        </group>

        <group name="cube_26" position={[0, 1.01, 1.01]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials['Yellow.003']} />
          <mesh name="Cube057_1" geometry={nodes.Cube057_1.geometry} material={materials['red.005']} />
        </group>

        <group name="cube_27" position={[1.01, 1.01, 1.01]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh name="Cube063" geometry={nodes.Cube063.geometry} material={materials['Yellow.009']} />
          <mesh name="Cube063_1" geometry={nodes.Cube063_1.geometry} material={materials['red.006']} />
          <mesh name="Cube063_2" geometry={nodes.Cube063_2.geometry} material={materials['green.006']} />
        </group>

      
    </group>
  )
});

useGLTF.preload('/cube.glb')
